"""add_conversation_sessions

Revision ID: ad58d88f08ed
Revises: 
Create Date: 2025-12-09 22:39:29.505170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad58d88f08ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=True),
    sa.Column('collected_data', sa.JSON(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('application_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('processing_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_conversation_sessions_session_id'), 'conversation_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_sessions_session_id'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
